config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :student_courses
    resources :students
    resources :courses
    resources :teacher_courses
    resources :teachers
    resources :lessons
    resources :buildings
    resources :rooms
    resources :dashboard

    root to: 'dashboard#show'
  end

  resources :buildings_preview
  resources :rooms_preview

  get '/buildings_preview/:id/today' => 'buildings_preview#today', :as => :today_action

  root to: 'buildings_preview#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :rooms

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true


end

app/models/course.rb
class Course < ApplicationRecord
  has_many :teacher_courses
  has_many :teachers, through: :teacher_courses
  has_many :lessons

  has_many :student_courses
  has_many :students, through: :student_courses

  extend Enumerize

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true
  validates :study_type_enum, presence: true
  validates :language_enum, presence: true

  enumerize :study_type_enum, in: {czech: "czech", english: "english"}

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :room
  belongs_to :teacher
  belongs_to :course

  validates :start_at, presence: true
  validates :end_at, presence: true
  validates :duration, presence: false
  validates :teacher_id, presence: true
  validates :room_id, presence: true
  validates :course_id, presence: true

  TEACHERS_NAMES = {}
  teachers = Teacher.all
  teachers.each do |b|
    TEACHERS_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end

  COURSE_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSE_NAMES["#{b.title}"] = b.id
  end

  ROOMS_NAMES = {}
  rooms = Room.all
  rooms.each do |b|
    ROOMS_NAMES["#{b.title}"] = b.id
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building
  has_many :lessons

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true
  validates :building_id, presence: true

  BUILDING_NAMES = {}
  buildings = Building.all
  buildings.each do |b|
    BUILDING_NAMES["#{b.title}"] = b.id
  end

end

app/models/student.rb
class Student < ApplicationRecord

  has_many :student_courses
  has_many :courses, through: :student_courses

  extend Enumerize

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: false

  enumerize :study_type_enum, in: {czech: "czech", english: "english"}
  enumerize :language_enum, in: {full_time: "full_time", part_time: "part_time"}


end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course

  validates :student_id, presence: true
  validates :course_id, presence: true

  COURSE_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSE_NAMES["#{b.title}"] = b.id
  end


  STUDENT_NAMES = {}
  students = Student.all
  students.each do |b|
    STUDENT_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end


end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :lessons
  has_many :teacher_courses
  has_many :courses, through: :teacher_courses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: false

end

app/models/teacher_course.rb
class TeacherCourse < ApplicationRecord
  belongs_to :teacher
  belongs_to :course

  validates :teacher_id, presence: true
  validates :course_id, presence: true

  COURSES_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSES_NAMES["#{b.title}"] = b.id
  end

  TEACHERS_NAMES = {}
  teachers = Teacher.all
  teachers.each do |b|
    TEACHERS_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end

end

app/controllers/admin/rooms_controller.rb
module Admin
class RoomsController < Admin::AdminController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to [:admin,@room], notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to [:admin,@room], notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to [:admin,rooms_url], notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :code, :building_id)
    end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/buildings_preview_helper.rb
module BuildingsPreviewHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/rooms_preview_helper.rb
module RoomsPreviewHelper
end

app/helpers/student_courses_helper.rb
module StudentCoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_courses_helper.rb
module TeacherCoursesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admin/rooms/_form.html.erb
<%= simple_form_for([:admin,@room]) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :code %>
      <%= f.input :building_id, :collection => Room::BUILDING_NAMES.sort.map {|k,v| [k,v]} %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>

<% end %>

app/views/admin/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', [:admin,@room] %> |
<%= link_to 'Back', admin_rooms_path %>

app/views/admin/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Code string</th>
      <th>Building</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.title %></td>
        <td><%= room.code %></td>
        <td><%= room.building_id %></td>
        <td><%= link_to 'Show', [:admin, room] %></td>
        <td><%= link_to 'Edit', edit_admin_room_path(room) %></td>
        <td><%= link_to 'Destroy', [:admin,room], method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_admin_room_path %>

app/views/admin/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', admin_rooms_path %>

app/views/admin/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Code string:</strong>
  <%= @room.code %>
</p>

<p>
  <strong>Building:</strong>
  <%= @room.building_id %>
</p>

<%= link_to 'Edit', edit_admin_room_path(@room) %> |
<%= link_to 'Back', admin_rooms_path %>