config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :student_courses
    resources :students
    resources :courses
    resources :teacher_courses
    resources :teachers
    resources :lessons
    resources :buildings
    resources :rooms
    resources :dashboard

    root to: 'dashboard#show'
  end

  resources :buildings_preview
  resources :rooms_preview

  get '/buildings_preview/:id/today' => 'buildings_preview#today', :as => :today_action

  root to: 'buildings_preview#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :rooms

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true


end

app/models/course.rb
class Course < ApplicationRecord
  has_many :teacher_courses
  has_many :teachers, through: :teacher_courses
  has_many :lessons

  has_many :student_courses
  has_many :students, through: :student_courses

  extend Enumerize

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true
  validates :study_type_enum, presence: true
  validates :language_enum, presence: true

  enumerize :study_type_enum, in: {czech: "czech", english: "english"}

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :room
  belongs_to :teacher
  belongs_to :course

  validates :start_at, presence: true
  validates :end_at, presence: true
  validates :duration, presence: false
  validates :teacher_id, presence: true
  validates :room_id, presence: true
  validates :course_id, presence: true

  TEACHERS_NAMES = {}
  teachers = Teacher.all
  teachers.each do |b|
    TEACHERS_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end

  COURSE_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSE_NAMES["#{b.title}"] = b.id
  end

  ROOMS_NAMES = {}
  rooms = Room.all
  rooms.each do |b|
    ROOMS_NAMES["#{b.title}"] = b.id
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building
  has_many :lessons

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true
  validates :building_id, presence: true

  BUILDING_NAMES = {}
  buildings = Building.all
  buildings.each do |b|
    BUILDING_NAMES["#{b.title}"] = b.id
  end

end

app/models/student.rb
class Student < ApplicationRecord

  has_many :student_courses
  has_many :courses, through: :student_courses

  extend Enumerize

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: false

  enumerize :study_type_enum, in: {czech: "czech", english: "english"}
  enumerize :language_enum, in: {full_time: "full_time", part_time: "part_time"}


end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course

  validates :student_id, presence: true
  validates :course_id, presence: true

  COURSE_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSE_NAMES["#{b.title}"] = b.id
  end


  STUDENT_NAMES = {}
  students = Student.all
  students.each do |b|
    STUDENT_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end


end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :lessons
  has_many :teacher_courses
  has_many :courses, through: :teacher_courses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: false

end

app/models/teacher_course.rb
class TeacherCourse < ApplicationRecord
  belongs_to :teacher
  belongs_to :course

  validates :teacher_id, presence: true
  validates :course_id, presence: true

  COURSES_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSES_NAMES["#{b.title}"] = b.id
  end

  TEACHERS_NAMES = {}
  teachers = Teacher.all
  teachers.each do |b|
    TEACHERS_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end

end

app/controllers/admin/students_controller.rb
module Admin
class StudentsController < Admin::AdminController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to [:admin,@student], notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to [:admin,@student], notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to [:admin,students_url], notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :study_type_enum)
    end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/buildings_preview_helper.rb
module BuildingsPreviewHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/rooms_preview_helper.rb
module RoomsPreviewHelper
end

app/helpers/student_courses_helper.rb
module StudentCoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_courses_helper.rb
module TeacherCoursesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admin/students/_form.html.erb
<%= simple_form_for([:admin,@student]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :study_type_enum %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', [:admin,@student] %> |
<%= link_to 'Back', admin_students_path %>

app/views/admin/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Study type enum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.email %></td>
        <td><%= student.study_type_enum %></td>
        <td><%= link_to 'Show', [:admin,student] %></td>
        <td><%= link_to 'Edit', edit_admin_student_path(student) %></td>
        <td><%= link_to 'Destroy', [:admin,student], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_admin_student_path %>

app/views/admin/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', admin_students_path %>

app/views/admin/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Study type enum:</strong>
  <%= @student.study_type_enum %>
</p>

<%= link_to 'Edit', edit_admin_student_path(@student) %> |
<%= link_to 'Back', admin_students_path %>