config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :student_courses
    resources :students
    resources :courses
    resources :teacher_courses
    resources :teachers
    resources :lessons
    resources :buildings
    resources :rooms
    resources :dashboard

    root to: 'dashboard#show'
  end

  resources :buildings_preview
  resources :rooms_preview

  get '/buildings_preview/:id/today' => 'buildings_preview#today', :as => :today_action

  root to: 'buildings_preview#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :rooms

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true


end

app/models/course.rb
class Course < ApplicationRecord
  has_many :teacher_courses
  has_many :teachers, through: :teacher_courses
  has_many :lessons

  has_many :student_courses
  has_many :students, through: :student_courses

  extend Enumerize

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true
  validates :study_type_enum, presence: true
  validates :language_enum, presence: true

  enumerize :study_type_enum, in: {czech: "czech", english: "english"}

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :room
  belongs_to :teacher
  belongs_to :course

  validates :start_at, presence: true
  validates :end_at, presence: true
  validates :duration, presence: false
  validates :teacher_id, presence: true
  validates :room_id, presence: true
  validates :course_id, presence: true

  TEACHERS_NAMES = {}
  teachers = Teacher.all
  teachers.each do |b|
    TEACHERS_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end

  COURSE_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSE_NAMES["#{b.title}"] = b.id
  end

  ROOMS_NAMES = {}
  rooms = Room.all
  rooms.each do |b|
    ROOMS_NAMES["#{b.title}"] = b.id
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building
  has_many :lessons

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true
  validates :building_id, presence: true

  BUILDING_NAMES = {}
  buildings = Building.all
  buildings.each do |b|
    BUILDING_NAMES["#{b.title}"] = b.id
  end

end

app/models/student.rb
class Student < ApplicationRecord

  has_many :student_courses
  has_many :courses, through: :student_courses

  extend Enumerize

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: false

  enumerize :study_type_enum, in: {czech: "czech", english: "english"}
  enumerize :language_enum, in: {full_time: "full_time", part_time: "part_time"}


end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course

  validates :student_id, presence: true
  validates :course_id, presence: true

  COURSE_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSE_NAMES["#{b.title}"] = b.id
  end


  STUDENT_NAMES = {}
  students = Student.all
  students.each do |b|
    STUDENT_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end


end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :lessons
  has_many :teacher_courses
  has_many :courses, through: :teacher_courses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: false

end

app/models/teacher_course.rb
class TeacherCourse < ApplicationRecord
  belongs_to :teacher
  belongs_to :course

  validates :teacher_id, presence: true
  validates :course_id, presence: true

  COURSES_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSES_NAMES["#{b.title}"] = b.id
  end

  TEACHERS_NAMES = {}
  teachers = Teacher.all
  teachers.each do |b|
    TEACHERS_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end

end

app/controllers/admin/buildings_controller.rb
module Admin
  class BuildingsController < Admin::AdminController
    before_action :set_building, only: [:show, :edit, :update, :destroy]

    # GET /buildings
    # GET /buildings.json
    def index
      @buildings = Building.all
    end

    # GET /buildings/1
    # GET /buildings/1.json
    def show

      @rooms = Room.all
    end

    # GET /buildings/new
    def new
      @building = Building.new
    end

    # GET /buildings/1/edit
    def edit
    end

    # POST /buildings
    # POST /buildings.json
    def create
      @building = Building.new(building_params)

      respond_to do |format|
        if @building.save
          format.html {redirect_to [:admin,@building], notice: 'Building was successfully created.'}
          format.json {render :show, status: :created, location: @building}
        else
          format.html {render :new}
          format.json {render json: @building.errors, status: :unprocessable_entity}
        end
      end
    end

    # PATCH/PUT /buildings/1
    # PATCH/PUT /buildings/1.json
    def update
      respond_to do |format|
        if @building.update(building_params)
          format.html {redirect_to [:admin,@building], notice: 'Building was successfully updated.'}
          format.json {render :show, status: :ok, location: @building}
        else
          format.html {render :edit}
          format.json {render json: @building.errors, status: :unprocessable_entity}
        end
      end
    end

    # DELETE /buildings/1
    # DELETE /buildings/1.json
    def destroy
      @building.destroy
      respond_to do |format|
        format.html {redirect_to [:admin,buildings_url], notice: 'Building was successfully destroyed.'}
        format.json {head :no_content}
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:title, :code)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/buildings_preview_helper.rb
module BuildingsPreviewHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/rooms_preview_helper.rb
module RoomsPreviewHelper
end

app/helpers/student_courses_helper.rb
module StudentCoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_courses_helper.rb
module TeacherCoursesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admin/buildings/_form.html.erb
<%= form_with(model: [:admin,@building], local: true) do |form| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :building_title %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :building_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Show', [:admin,@building] %> |
<%= link_to 'Back', admin_buildings_path %>

app/views/admin/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.title %></td>
        <td><%= building.code %></td>
        <td><%= link_to 'Show', [:admin,building] %></td>
        <td><%= link_to 'Edit', edit_admin_building_path(building) %></td>
        <td><%= link_to 'Destroy', [:admin,building], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_admin_building_path %>

app/views/admin/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form', building: @building %>

<%= link_to 'Back', admin_buildings_path %>

app/views/admin/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @building.title %>
</p>

<p>
  <strong>Code:</strong>
  <%= @building.code %>
</p>

<p>
  <strong>Rooms:</strong>
  <% @rooms.each do |room| %>
    <p>
  <%= room.title %>
  <%= room.code %>
    <p>
  <% end %>
</p>


<%= link_to 'Edit', edit_admin_building_path(@building) %> |
<%= link_to 'Back', admin_buildings_path %>