config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :student_courses
    resources :students
    resources :courses
    resources :teacher_courses
    resources :teachers
    resources :lessons
    resources :buildings
    resources :rooms
    resources :dashboard

    root to: 'dashboard#show'
  end

  resources :buildings_preview
  resources :rooms_preview

  get '/buildings_preview/:id/today' => 'buildings_preview#today', :as => :today_action

  root to: 'buildings_preview#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :rooms

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true


end

app/models/course.rb
class Course < ApplicationRecord
  has_many :teacher_courses
  has_many :teachers, through: :teacher_courses
  has_many :lessons

  has_many :student_courses
  has_many :students, through: :student_courses

  extend Enumerize

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true
  validates :study_type_enum, presence: true
  validates :language_enum, presence: true

  enumerize :study_type_enum, in: {czech: "czech", english: "english"}

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :room
  belongs_to :teacher
  belongs_to :course

  validates :start_at, presence: true
  validates :end_at, presence: true
  validates :duration, presence: false
  validates :teacher_id, presence: true
  validates :room_id, presence: true
  validates :course_id, presence: true

  TEACHERS_NAMES = {}
  teachers = Teacher.all
  teachers.each do |b|
    TEACHERS_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end

  COURSE_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSE_NAMES["#{b.title}"] = b.id
  end

  ROOMS_NAMES = {}
  rooms = Room.all
  rooms.each do |b|
    ROOMS_NAMES["#{b.title}"] = b.id
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building
  has_many :lessons

  validates :title, presence: true
  validates :code, presence: true, uniqueness: true
  validates :building_id, presence: true

  BUILDING_NAMES = {}
  buildings = Building.all
  buildings.each do |b|
    BUILDING_NAMES["#{b.title}"] = b.id
  end

end

app/models/student.rb
class Student < ApplicationRecord

  has_many :student_courses
  has_many :courses, through: :student_courses

  extend Enumerize

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: false

  enumerize :study_type_enum, in: {czech: "czech", english: "english"}
  enumerize :language_enum, in: {full_time: "full_time", part_time: "part_time"}


end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course

  validates :student_id, presence: true
  validates :course_id, presence: true

  COURSE_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSE_NAMES["#{b.title}"] = b.id
  end


  STUDENT_NAMES = {}
  students = Student.all
  students.each do |b|
    STUDENT_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end


end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :lessons
  has_many :teacher_courses
  has_many :courses, through: :teacher_courses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: false

end

app/models/teacher_course.rb
class TeacherCourse < ApplicationRecord
  belongs_to :teacher
  belongs_to :course

  validates :teacher_id, presence: true
  validates :course_id, presence: true

  COURSES_NAMES = {}
  courses = Course.all
  courses.each do |b|
    COURSES_NAMES["#{b.title}"] = b.id
  end

  TEACHERS_NAMES = {}
  teachers = Teacher.all
  teachers.each do |b|
    TEACHERS_NAMES["#{b.first_name} #{b.last_name}"] = b.id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/rooms_preview_helper.rb
module RoomsPreviewHelper
end

app/helpers/student_courses_helper.rb
module StudentCoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_courses_helper.rb
module TeacherCoursesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
 <!DOCTYPE html>
  <html lang="en">

  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>

    <%= stylesheet_link_tag "customstyles" %>

    <meta charset="UTF-8">
    <title>Title</title>
  </head>

<body class="body">

<header class="mainHeader">
  <nav>
    <ul id="menu">
      <li id="name"> <%= link_to "WEB", root_path %></li>
      <li><%= link_to "Budovy", root_path %></li>
      <li><%= link_to "Dashboard", "/admin" %></li>
    </ul>
  </nav>

</header>
<header id="breadcrumbs">
  <%= link_to "Budovy", root_path %>
  <%
  if request.path.split("/")[1] == "rooms_preview" && request.path.split("/")[2]%>
  <%=  link_to "/ místnost", buildings_preview_path(:id => @thisRoom.building_id ) %>
  <% end %>

</header>
<section class="middleSidebar">
  <article id="mid">

    <br>
    <%
      if request.path.split("/")[1] == "admin"
        %>
        <%= link_to "Dashboard", "/admin" %>
        <%= link_to "Buildings (#{Building.all.count})", admin_buildings_path %>
        <%= link_to "Rooms (#{Room.all.count})", admin_rooms_path %>
        <%= link_to "Lessons (#{Lesson.all.count})", admin_lessons_path %>
        <%= link_to "Teachers (#{Teacher.all.count})", admin_teachers_path %>
        <%= link_to "Courses (#{Course.all.count})", admin_courses_path %>
        <%= link_to "Teacher-Course (#{TeacherCourse.all.count})", admin_teacher_courses_path %>
        <%= link_to "Students (#{Student.all.count})", admin_students_path %>
        <%= link_to "Students-Course (#{StudentCourse.all.count})", admin_student_courses_path %>
        <hr>
      <%
      end
      %>
    <%= yield %>

  </article>
</section>
<footer id="customFooter">
  © copyrigt
</footer>
</body>

</html>